
name: NIC crawl
on:
  schedule:
    - cron:  '0 * * * *'   # cada hora en punto
  workflow_dispatch:       # permite ejecutar manualmente

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar deps
        run: |
          npm init -y
          npm install fast-xml-parser node-fetch@3 jsdom

      - name: Crear directorio de datos
        run: mkdir -p public/data

      - name: Ejecutar script
        run: node scripts/nic-to-json.mjs

      - name: Validar JSON
        run: |
          # Check if the JSON file is valid
          cat public/data/latest.json | jq empty && echo "✅ JSON is valid" || exit 1

      - name: Commit y push si hay cambios
        run: |
          git config user.name  "NIC Bot"
          git config user.email "bot@eligetuhosting.cl"
          git add public/data/latest.json
          git diff --cached --quiet || git commit -m "chore: update latest domains [skip ci]"
          git push

      - name: Notificar en caso de fallo
        if: failure()
        run: |
          echo "El script de actualización de dominios ha fallado. Por favor, revisa los logs."
          # Aquí se podría agregar una notificación por correo electrónico o Discord
          # por ejemplo usando curl para llamar a un webhook
