name: NIC crawl

on:
  schedule:
    - cron: '0 * * * *'          # cada hora (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Instalar dependencias
        run: npm install --no-save fast-xml-parser@4 node-fetch@3 jsdom

      - name: Marcar el proyecto como ES Modules      # ← nuevo
        run: npm pkg set type=module

      - name: Crear carpeta data
        run: mkdir -p public/data

      - name: Ejecutar scraper NIC.cl
        run: node scripts/nic-to-json.mjs

      - name: Diff rápido
        run: |
          echo "HEAD:"
          head -3 public/data/latest.json
          git diff --color -- public/data/latest.json | head || true

      - name: Commit y push si cambia
        run: |
          git config user.name  "NIC Bot"
          git config user.email "bot@eligetuhosting.cl"
          git add public/data/latest.json
          if ! git diff --cached --quiet; then
            git commit -m "chore(domains): update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
            echo "✅ Cambios subidos."
          else
            echo "ℹ️  Sin cambios; no se hace push."
          fi

