
name: NIC crawl

on:
  schedule:
    - cron: '0 * * * *'          # cada hora (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Instalar dependencias
        run: npm install --no-save fast-xml-parser@4 node-fetch@3 jsdom

      - name: Marcar el proyecto como ES Modules      # ← nuevo
        run: npm pkg set type=module

      - name: Crear carpeta data y feeds
        run: |
          mkdir -p public/data
          mkdir -p public/feed

      - name: Ejecutar scraper NIC.cl
        run: node scripts/nic-to-json.mjs

      - name: Generar RSS feed
        run: node scripts/generate-rss.mjs 

      - name: Verificar dominios capturados
        run: |
          echo "📊 Dominios en latest.json:"
          if [ -f public/data/latest.json ]; then
            head -3 public/data/latest.json
            echo "Total dominios: $(jq '.domains | length' public/data/latest.json 2>/dev/null || echo 'Error leyendo JSON')"
          else
            echo "❌ Archivo latest.json no encontrado"
          fi

      - name: Commit feeds y datos
        run: |
          git config user.name  "NIC Bot"
          git config user.email "bot@eligetuhosting.cl"
          git add public/data/latest.json public/feed/latest-domains.xml
          if ! git diff --cached --quiet; then
            git commit -m "chore(domains): update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
            echo "✅ Feeds actualizados y subidos."
          else
            echo "ℹ️  Sin cambios en feeds."
          fi

      - name: Generar sitemap
        run: node scripts/generate-sitemap.mjs
        continue-on-error: true

      - name: Commit sitemap
        run: |
          git config user.name  "NIC Bot"
          git config user.email "bot@eligetuhosting.cl"
          if [ -f public/sitemap.xml ]; then
            git add public/sitemap.xml
            if ! git diff --cached --quiet; then
              git commit -m "chore(sitemap): update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
              git push
              echo "✅ Sitemap actualizado y subido."
            else
              echo "ℹ️  Sin cambios en sitemap."
            fi
          else
            echo "⚠️  Sitemap no generado, saltando commit."
          fi
